In [184]:
import pandas as pd

url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Resgression/Salary_Data2.csv"
data = pd.read_csv(url)
data

YearsExperience EducationLevel City  Salary
0               3.0             大學  城市A    45.9
1               7.8           碩士以上  城市C    80.5
2               2.3           高中以下  城市A    25.2
3               5.1           高中以下  城市A    30.4
4              10.0           碩士以上  城市B    65.7
5               1.2           碩士以上  城市C    60.8
6               8.6             大學  城市C    50.1
7               6.9           碩士以上  城市A    70.3
8               4.2             大學  城市A    40.7
9               2.4           高中以下  城市A    28.1
10              5.3           高中以下  城市A    32.0
11              3.9             大學  城市A    48.3
12              7.2           碩士以上  城市C    84.2
13             10.0           碩士以上  城市B    70.9
14              1.5           碩士以上  城市C    62.4
15              8.4             大學  城市C    55.6
16              6.5           碩士以上  城市A    72.7
17              4.8             大學  城市A    42.9
18              2.1           高中以下  城市A    26.5
19              5.2           高中以下  城市A    31.6
20              3.5             大學  城市A    43.8
21              7.6           碩士以上  城市C    78.3
22             10.0           碩士以上  城市B    63.6
23              1.8           碩士以上  城市C    58.0
24              8.2             大學  城市C    48.3
25              6.3           碩士以上  城市A    68.4
26              4.6             大學  城市A    38.5
27              2.5           高中以下  城市A    24.9
28              5.0           高中以下  城市A    29.7
29              3.6             大學  城市A    41.6
30              7.4           碩士以上  城市C    76.9
31             10.0           碩士以上  城市B    60.2
32              1.7           碩士以上  城市C    56.3
33              8.0             大學  城市C    45.2
34              6.1           碩士以上  城市A    65.9
35              4.3             大學  城市A    36.7

In [185]:
data["EducationLevel"] = data["EducationLevel"].map({"高中以下": 0, "大學": 1, "碩士以上": 2})
data

YearsExperience  EducationLevel City  Salary
0               3.0               1  城市A    45.9
1               7.8               2  城市C    80.5
2               2.3               0  城市A    25.2
3               5.1               0  城市A    30.4
4              10.0               2  城市B    65.7
5               1.2               2  城市C    60.8
6               8.6               1  城市C    50.1
7               6.9               2  城市A    70.3
8               4.2               1  城市A    40.7
9               2.4               0  城市A    28.1
10              5.3               0  城市A    32.0
11              3.9               1  城市A    48.3
12              7.2               2  城市C    84.2
13             10.0               2  城市B    70.9
14              1.5               2  城市C    62.4
15              8.4               1  城市C    55.6
16              6.5               2  城市A    72.7
17              4.8               1  城市A    42.9
18              2.1               0  城市A    26.5
19              5.2               0  城市A    31.6
20              3.5               1  城市A    43.8
21              7.6               2  城市C    78.3
22             10.0               2  城市B    63.6
23              1.8               2  城市C    58.0
24              8.2               1  城市C    48.3
25              6.3               2  城市A    68.4
26              4.6               1  城市A    38.5
27              2.5               0  城市A    24.9
28              5.0               0  城市A    29.7
29              3.6               1  城市A    41.6
30              7.4               2  城市C    76.9
31             10.0               2  城市B    60.2
32              1.7               2  城市C    56.3
33              8.0               1  城市C    45.2
34              6.1               2  城市A    65.9
35              4.3               1  城市A    36.7

In [186]:
from sklearn.preprocessing import OneHotEncoder

onehot_encoder = OneHotEncoder()
onehot_encoder.fit(data[["City"]])
city_encoded = onehot_encoder.transform(data[["City"]]).toarray()
city_encoded

array([[ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 1.00e+00,  0.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.00e+00],
       [ 0.00e+00,  1.00e+00,  0.00e+00],
       [ 0.00e+00,  0.00e+00,  1.0

In [187]:
data[["CityA", "CityB", "CityC"]] = city_encoded
data

YearsExperience  EducationLevel City  Salary  CityA  CityB  CityC
0               3.0               1  城市A    45.9    1.0    0.0    0.0
1               7.8               2  城市C    80.5    0.0    0.0    1.0
2               2.3               0  城市A    25.2    1.0    0.0    0.0
3               5.1               0  城市A    30.4    1.0    0.0    0.0
4              10.0               2  城市B    65.7    0.0    1.0    0.0
5               1.2               2  城市C    60.8    0.0    0.0    1.0
6               8.6               1  城市C    50.1    0.0    0.0    1.0
7               6.9               2  城市A    70.3    1.0    0.0    0.0
8               4.2               1  城市A    40.7    1.0    0.0    0.0
9               2.4               0  城市A    28.1    1.0    0.0    0.0
10              5.3               0  城市A    32.0    1.0    0.0    0.0
11              3.9               1  城市A    48.3    1.0    0.0    0.0
12              7.2               2  城市C    84.2    0.0    0.0    1.0
13             10.0               2  城市B    70.9    0.0    1.0    0.0
14              1.5               2  城市C    62.4    0.0    0.0    1.0
15              8.4               1  城市C    55.6    0.0    0.0    1.0
16              6.5               2  城市A    72.7    1.0    0.0    0.0
17              4.8               1  城市A    42.9    1.0    0.0    0.0
18              2.1               0  城市A    26.5    1.0    0.0    0.0
19              5.2               0  城市A    31.6    1.0    0.0    0.0
20              3.5               1  城市A    43.8    1.0    0.0    0.0
21              7.6               2  城市C    78.3    0.0    0.0    1.0
22             10.0               2  城市B    63.6    0.0    1.0    0.0
23              1.8               2  城市C    58.0    0.0    0.0    1.0
24              8.2               1  城市C    48.3    0.0    0.0    1.0
25              6.3               2  城市A    68.4    1.0    0.0    0.0
26              4.6               1  城市A    38.5    1.0    0.0    0.0
27              2.5               0  城市A    24.9    1.0    0.0    0.0
28              5.0               0  城市A    29.7    1.0    0.0    0.0
29              3.6               1  城市A    41.6    1.0    0.0    0.0
30              7.4               2  城市C    76.9    0.0    0.0    1.0
31             10.0               2  城市B    60.2    0.0    1.0    0.0
32              1.7               2  城市C    56.3    0.0    0.0    1.0
33              8.0               1  城市C    45.2    0.0    0.0    1.0
34              6.1               2  城市A    65.9    1.0    0.0    0.0
35              4.3               1  城市A    36.7    1.0    0.0    0.0

In [188]:
data = data.drop(["City", "CityC"], axis=1)
data

YearsExperience  EducationLevel  Salary  CityA  CityB
0               3.0               1    45.9    1.0    0.0
1               7.8               2    80.5    0.0    0.0
2               2.3               0    25.2    1.0    0.0
3               5.1               0    30.4    1.0    0.0
4              10.0               2    65.7    0.0    1.0
5               1.2               2    60.8    0.0    0.0
6               8.6               1    50.1    0.0    0.0
7               6.9               2    70.3    1.0    0.0
8               4.2               1    40.7    1.0    0.0
9               2.4               0    28.1    1.0    0.0
10              5.3               0    32.0    1.0    0.0
11              3.9               1    48.3    1.0    0.0
12              7.2               2    84.2    0.0    0.0
13             10.0               2    70.9    0.0    1.0
14              1.5               2    62.4    0.0    0.0
15              8.4               1    55.6    0.0    0.0
16              6.5               2    72.7    1.0    0.0
17              4.8               1    42.9    1.0    0.0
18              2.1               0    26.5    1.0    0.0
19              5.2               0    31.6    1.0    0.0
20              3.5               1    43.8    1.0    0.0
21              7.6               2    78.3    0.0    0.0
22             10.0               2    63.6    0.0    1.0
23              1.8               2    58.0    0.0    0.0
24              8.2               1    48.3    0.0    0.0
25              6.3               2    68.4    1.0    0.0
26              4.6               1    38.5    1.0    0.0
27              2.5               0    24.9    1.0    0.0
28              5.0               0    29.7    1.0    0.0
29              3.6               1    41.6    1.0    0.0
30              7.4               2    76.9    0.0    0.0
31             10.0               2    60.2    0.0    1.0
32              1.7               2    56.3    0.0    0.0
33              8.0               1    45.2    0.0    0.0
34              6.1               2    65.9    1.0    0.0
35              4.3               1    36.7    1.0    0.0

In [189]:
from sklearn.model_selection import train_test_split
x = data[["YearsExperience", "EducationLevel", "CityA", "CityB"]]
y = data["Salary"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

In [190]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [191]:
import numpy as np

w = np.array([1, 2, 3, 4])
b = 1
y_pred = (x_train*w).sum(axis=1) + b

In [192]:
((y_train - y_pred)**2).mean()

2729.861648680892

In [193]:
def compute_cost(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  cost = ((y - y_pred)**2).mean()
  return cost

In [194]:
w = np.array([0, 2, 2, 4])
b = 0
compute_cost(x_train, y_train, w, b)

2822.234209806599

In [195]:
y_pred=(x_train*w).sum(axis=1)+b
b_gradient = (y_pred - y_train).mean()
w_gradient = np.zeros(x_train.shape[1])
for i in range(x_train.shape[1]):
  w_gradient[i] = (x_train[:,i]*(y_pred - y_train)).mean()
w_gradient,b_gradient

(array([-6.35e+00, -1.26e+01,  1.02e+01, -1.77e+00]), -50.949999999999996)

In [196]:
def compute_gradient(x, y, w, b):
  y_pred = (x*w).sum(axis=1) + b
  w_gradient = np.zeros(x.shape[1])
  b_gradient = (y_pred - y).mean()
  for i in range(x.shape[1]):
    w_gradient[i] = (x[:, i]*(y_pred - y)).mean()

  return w_gradient, b_gradient

In [197]:
w = np.array([1, 2, 2, 4])
b = 1
compute_gradient(x_train,y_train,w,b)

(array([-5.35e+00, -1.22e+01,  9.62e+00, -1.12e+00]), -49.95)

In [198]:
w = np.array([1, 2, 2, 4])
b = 1
learing_rate= 0.001
w_gradient,b_gradient = compute_gradient(x_train,y_train,w,b)
print(compute_cost(x,y,w,b))
w = w - w_gradient*learing_rate
b = b - b_gradient*learing_rate
w,b
print(compute_cost(x,y,w,b))

1925.1341666666663
1917.3101649074104


In [199]:
np.set_printoptions(formatter={'float': '{: .2e}'.format})
def gradient_descent(x, y, w_init, b_init, learning_rate, cost_function, gradient_function, run_iter, p_iter=1000):

  c_hist = []
  w_hist = []
  b_hist = []

  w = w_init
  b = b_init

  for i in range(run_iter):
    w_gradient, b_gradient = gradient_function(x, y, w, b)

    w = w - w_gradient*learning_rate
    b = b - b_gradient*learning_rate
    cost = cost_function(x, y, w, b)

    w_hist.append(w)
    b_hist.append(b)
    c_hist.append(cost)

    if i%p_iter == 0:
      print(f"Iteration {i:5} : Cost {cost: .4e}, w: {w}, b: {b: .2e}, w_gradient: {w_gradient}, b_gradient: {b_gradient: .2e}")

  return w, b, w_hist, b_hist, c_hist

In [200]:
w_init = np.array([1, 2, 2, 4])
b_init = 0
learning_rate = 1.0e-2
run_iter = 10000

w_final, b_final, w_hist, b_hist, c_hist = gradient_descent(x_train, y_train, w_init, b_init, learning_rate, compute_cost, compute_gradient, run_iter)

Iteration     0 : Cost  2.7535e+03, w: [ 1.05e+00  2.12e+00  1.90e+00  4.01e+00], b:  5.10e-01, w_gradient: [-5.35e+00 -1.22e+01  9.62e+00 -1.12e+00], b_gradient: -5.10e+01
Iteration  1000 : Cost  2.5326e+01, w: [ 3.73e+00  1.39e+01 -1.82e+00 -3.51e+00], b:  5.09e+01, w_gradient: [-9.61e-02 -6.24e-02 -8.60e-02  7.25e-02], b_gradient: -2.20e-03
Iteration  2000 : Cost  2.5223e+01, w: [ 4.09e+00  1.41e+01 -1.49e+00 -3.76e+00], b:  5.09e+01, w_gradient: [-8.25e-03 -5.10e-03 -7.72e-03  5.60e-03], b_gradient: -9.50e-08
Iteration  3000 : Cost  2.5222e+01, w: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, w_gradient: [-6.98e-04 -4.34e-04 -6.57e-04  4.72e-04], b_gradient: -4.10e-12
Iteration  4000 : Cost  2.5222e+01, w: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, w_gradient: [-5.92e-05 -3.68e-05 -5.57e-05  4.00e-05], b_gradient: -3.48e-13
Iteration  5000 : Cost  2.5222e+01, w: [ 4.12e+00  1.41e+01 -1.46e+00 -3.78e+00], b:  5.09e+01, w_gradient: [-5.02e-06 -3.12e-06 -4.73e

In [201]:
w_final, b_final

(array([ 4.12e+00,  1.41e+01, -1.46e+00, -3.78e+00]), 50.949999999999655)

In [202]:
y_pred = (w_final*x_test).sum(axis=1) + b_final
pd.DataFrame({
    "y_pred": y_pred,
    "y_test": y_test
})

y_pred  y_test
20  44.035070    43.8
16  67.440313    72.7
5   61.954972    60.8
27  23.802655    24.9
32  62.748179    56.3
2   23.485373    25.2
1   72.425307    80.5
7   68.074879    70.3

In [203]:
compute_cost(x_test, y_test, w_final, b_final)

18.116060544218655

In [204]:
# 5.3 碩士以上 城市A
# 7.2 高中以下 城市B
x_real = np.array([[5.3, 2, 1, 0], [7.2, 0, 0, 1]])
x_real = scaler.transform(x_real)
y_real = (w_final*x_real).sum(axis=1) + b_final
y_real

array([ 6.55e+01,  2.34e+01])